### ISSUE TITLE
Unable to write to file continued

### ISSUE THREAD

**Issue by ri-nath** [4321ba/noteblock_music_yoinker#2] opened 2020-11-20 21:53 UTC
Hi, you identified the issue in issue #1 but forgot to compile a new `jar` file. 
I'm creating as an issue and not a PR as I can't seem to compile it on my machine as I'm missing some dependencies or something.

**Comment by 4321ba** [comment] 2020-11-21 17:38
Hi! Yes, I was waiting, because there may be some other issues before I release a new jar file, but I understand that this issue makes the program unusable on Windows, so I'll try compiling it again (I actually have no idea what I'm doing). I also have an issue while compiling, it's complaining about DateTimeFormatter, I think it needs to be imported first. I'll try fixing it.

**Comment by 4321ba** [comment] 2020-11-21 17:52
Github closed this because of the commit, but please test the 1.1 release and if it works, I'll close this.

**Comment by 4321ba** [comment] 2020-12-11 07:53
@faultymotor Does it work now? There's also a release for 1.12, it has the fix too.

**Comment by 4321ba** [comment] 2021-01-07 16:06
I'm closing this because of inactivity but feel free to reopen it or create a new one if the issue is still present.

**Closed as completed by 4321ba** 2021-01-07 16:06 UTC
